// Generated by CoffeeScript 1.7.1
(function() {
  var client, config, redis, redis_set;

  redis = require('redis');
  config = require('../config');

  redis_set = config.options.redis_set || 'signees';

  client = redis.createClient();

  client.on('error', function(err) {
    return console.log("Redis Error: " + err);
  });

  exports.getSignees = function(callback) {
    return client.SMEMBERS(redis_set, function(err, replies) {
      if (err) {
        return callback([]);
      } else {
        return callback(replies);
      }
    });
  };

  exports.addSignee = function(github_username, callback) {
    return client.SADD(redis_set, github_username, function(err, replies) {
      if (err) {
        return callback(false);
      } else {
        return callback(true);
      }
    });
  };

}).call(this);
