// Generated by CoffeeScript 1.7.1
(function() {
  var DB, HOST, PORT, SET, client, config, redis;

  redis = require('redis');
  config = require('../config');
  config.options.redis = config.options.redis || {};

  DB   = config.options.redis.database || '0';
  HOST = config.options.redis.host || '127.0.0.1';
  PORT = config.options.redis.port || '6379';
  SET  = config.options.redis.contractorSet || 'signees';
  OPTS = config.options.redis.options || {};

  client = redis.createClient(PORT, HOST, OPTS);

  client.on('error', function(err) {
    console.log("Redis Error: " + err);
  });
  client.select(DB);

  exports.getSignees = function(callback) {
    return client.SMEMBERS(SET, function(err, replies) {
      if (err) {
        throw(err);
        return callback([]);
      } else {
        return callback(replies);
      }
    });
  };

  exports.addSignee = function(github_username, callback) {
    return client.SADD(SET, github_username, function(err, replies) {
      if (err) {
        throw(err);
        return callback(false);
      } else {
        return callback(true);
      }
    });
  };

}).call(this);
